[package]
name = "ultros-api-types"
version = "0.1.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.152", features = ["derive", "rc"]}
chrono = {version = "0.4.23", features = ["serde", "rkyv-64", "rkyv-validation"]}
thiserror = "1.0.40"
rkyv = { version = "0.7.42", features = ["validation", "size_64", "hashbrown"], default-features = false, optional = true }

[features]
default = []
rkyv = ["dep:rkyv"]
