[package]
name = "price-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
universalis = { path = "../universalis" }
tokio = { workspace = true, features = ["full"] }
clap = { version = "4.0.18", features = ["derive"] }
